### ISSUE TITLE
Determine the environment

### ISSUE THREAD

**Issue by zcc720** [Cw-zero/TensorRT_yolo3_module#3]
**Can you share your TensorRT&onnx&pytorch version?** 
When I run, I encounter the following errors，I suspect that different versions resulted.
onnx 1.5
Tensorrt TensorRT-5.1.5.0
Traceback (most recent call last):
File "weight_to_onnx.py", line 670, in
main()
File "weight_to_onnx.py", line 663, in main
onnx.checker.check_model(yolov3_model_def)
File "/home/zcc/anaconda3/envs/py27/lib/python2.7/site-packages/onnx/checker.py", line 86, in check_model
C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Op registered for Upsample is depracted in domain_version of 10

**Comment by ruyijidan** [comment]
try onnx=>1.2 or 1.0

**Comment by intersoulest** [comment]
why have the error ? I hope to solve the problem.
Traceback (most recent call last):
  File "/media/nvidia/6677-DC2A1/TensorRT_yolo3_module-master/weight_to_onnx.py", line 670, in <module>
    main()
  File "/media/nvidia/6677-DC2A1/TensorRT_yolo3_module-master/weight_to_onnx.py", line 621, in main
    with python2. The rest of this sample can be run with either version of python")
Exception: This is script is only compatible with python2, please re-run this script     with python2. The rest of this sample can be run with either version of python
